compose_base_path: /home/jackson/composectl

network:
  name: secure-bridge
  driver: bridge

services:
  enable:
    - bind
    - dhcp
    - traefik
    - homepage
    - it-tools
    - zeek-filebeat
    - logstash-kafka
    - authentik
  disable:
    - vaultwarden
