services:
  bind:
    container_name: bind
    image: "ubuntu/bind9:latest"
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./config/named.conf:/etc/bind/named.conf
      - ./zones:/etc/bind/zones/managed
      - /opt/storage/bind/cache:/var/cache/bind
      - /opt/storage/bind/records:/var/lib/bind
    restart: always
    networks:
      - secure-network

networks:
  secure-network:
    external: true
    name: ${CONTAINER_NETWORK}
