# Reference: https://gethomepage.dev/installation/docker/#using-environment-secrets

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./bookmarks.yaml:/app/config/bookmarks.yaml
      - ./services.yaml:/app/config/services.yaml
      - ./settings.yaml:/app/config/settings.yaml
      - ./widgets.yaml:/app/config/widgets.yaml
      - ./docker.yaml:/app/config/docker.yaml
      - ./kubernetes.yaml:/app/config/kubernetes.yaml
      - /opt/storage/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: 0
      PGID: 0
    networks:
      - secure-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-http.rule=Host(`home.lxa.com`)"
      - "traefik.http.routers.homepage-http.entrypoints=web"
      - "traefik.http.routers.homepage-https.rule=Host(`home.linuxastra.in`)"
      - "traefik.http.routers.homepage-https.entrypoints=websecure"
      - "traefik.http.routers.homepage-https.tls=true"
      - "traefik.http.routers.homepage-https.tls.certresolver=letsencrypt"
    restart: always

networks:
  secure-network:
    external: true
    name: ${CONTAINER_NETWORK}
