services:
  stash:
    image: ghcr.io/umputun/stash:v0.19.0
    container_name: stash
    restart: unless-stopped

    command:
      - /srv/stash
      - server
      - --db=/srv/data/stash.db
      - --auth.file=/srv/data/stash-auth.yml
      - --auth.hot-reload

    ports:
      - "8080:8080"

    volumes:
      - ./data:/srv/data
      - ./config/stash-auth.yml:/srv/data/stash-auth.yml