services:
  dhcp:
    build: .
    container_name: dhcp
    restart: always
    network_mode: "host"
    volumes:
      - ./config/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - /opt/storage/dhcp:/var/lib/dhcp
    environment:
      - INTERFACES=
    cap_add:
      - NET_ADMIN
    privileged: true
