services:
  it-tools:
    container_name: it-tools
    stdin_open: true
    tty: true
    image: corentinth/it-tools
    networks:
      - secure-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ittools-http.rule=Host(`ittools.lxa.com`)"
      - "traefik.http.routers.ittools-http.entrypoints=web"
    restart: always

networks:
  secure-network:
    external: true
    name: ${CONTAINER_NETWORK}
