services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      PUID: 0
      PGID: 0
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ./config:/config
      - /opt/storage/traefik/logs:/remotelogs/traefik:ro
      - ./custom-cont-init.d:/custom-cont-init.d:ro
    restart: unless-stopped
