services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yaml:ro
      - /opt/storage/traefik/letsencrypt:/letsencrypt
    networks:
      - secure-network
    restart: unless-stopped

networks:
  secure-network:
    external: true
    name: ${CONTAINER_NETWORK}
